"""add user email unique constraint to prevent duplication

Revision ID: 2f6d11227248
Revises: ee4c5bb927da
Create Date: 2026-09-11 10:23:51.341636

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f6d11227248"
down_revision: str | Sequence[str] | None = "ee4c5bb927da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_users_user_email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_user_email", "users", type_="unique")
    # ### end Alembic commands ###
