"""add role column to organization_memberships table

Revision ID: ee4c5bb927da
Revises: 3e9456bcba04
Create Date: 2026-09-09 17:09:40.365291

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee4c5bb927da"
down_revision: str | Sequence[str] | None = "3e9456bcba04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_memberships",
        sa.Column(
            "role", sa.String(length=20), server_default="operator", nullable=False
        ),
    )
    op.create_check_constraint(
        "ck_organization_memberships_role",
        "organization_memberships",
        "role IN ('operator', 'admin')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_organization_memberships_role", "organization_memberships", type_="check"
    )
    op.drop_column("organization_memberships", "role")
    # ### end Alembic commands ###
